# Generated by Django 5.2.5 on 2025-11-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='tipo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('CHEQUE', 'Cheque'), ('DIGITAL', 'Pago Digital'), ('OTRO', 'Otro')], help_text='Tipo de método de pago: Transferencia, Efectivo', max_length=30),
        ),
    ]
