# Generated by Django 5.2.5 on 2025-10-15 04:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_labor', models.DateField(help_text='Fecha en que se realiza la labor')),
                ('labor', models.CharField(choices=[('SIEMBRA', 'Siembra'), ('RIEGO', 'Riego'), ('FERTILIZACION', 'Fertilización'), ('COSECHA', 'Cosecha'), ('FUMIGACION', 'Fumigación')], help_text='Tipo de labor agrícola', max_length=50)),
                ('estado', models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PLANIFICADA', help_text='Estado actual de la labor', max_length=50)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales de la labor', null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('campania', models.ForeignKey(blank=True, help_text='campania a la que pertenece esta labor (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperativa.campaign')),
                ('parcela', models.ForeignKey(blank=True, help_text='Parcela en la que se realiza la labor (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperativa.parcela')),
            ],
            options={
                'verbose_name': 'Labor Agrícola',
                'verbose_name_plural': 'Labores Agrícolas',
                'db_table': 'labor',
                'ordering': ['-fecha_labor'],
            },
        ),
        migrations.CreateModel(
            name='ProductoCosechado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cosecha', models.DateField(help_text='Fecha en que se realizó la cosecha')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad cosechada', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='La cantidad no puede ser negativa')])),
                ('unidad_medida', models.CharField(help_text='Unidad de medida (kg, toneladas, quintales, etc.)', max_length=20, validators=[django.core.validators.RegexValidator(message='Unidad de medida solo puede contener letras, números, espacios y barras', regex='^[a-zA-ZÀ-ÿ0-9\\s\\/]+$')])),
                ('calidad', models.CharField(help_text='Calidad del producto cosechado (ej: Premium, Estándar, etc.)', max_length=50, validators=[django.core.validators.RegexValidator(message='Calidad solo puede contener letras, números, espacios, guiones y puntos', regex='^[a-zA-ZÀ-ÿ0-9\\s\\-\\.]+$')])),
                ('estado', models.CharField(choices=[('En Almacén', 'En Almacén'), ('Vendido', 'Vendido'), ('Procesado', 'Procesado'), ('Vencido', 'Vencido'), ('En revision', 'En revision')], default='En Almacén', help_text='Estado actual del producto cosechado', max_length=50)),
                ('lote', models.FloatField(help_text='Número de lote del producto', validators=[django.core.validators.MinValueValidator(0, message='El lote no puede ser negativo')])),
                ('ubicacion_almacen', models.CharField(help_text='Ubicación física en el almacén', max_length=100, validators=[django.core.validators.RegexValidator(message='Ubicación solo puede contener letras, números, espacios, guiones, puntos y barras', regex='^[a-zA-ZÀ-ÿ0-9\\s\\-\\.\\/]+$')])),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el producto cosechado', null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('campania', models.ForeignKey(blank=True, help_text='campania a la que pertenece el producto (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_cosechados', to='cooperativa.campaign')),
                ('cultivo', models.ForeignKey(help_text='Cultivo del que se obtuvo el producto', on_delete=django.db.models.deletion.CASCADE, related_name='productos_cosechados', to='cooperativa.cultivo')),
                ('labor', models.OneToOneField(help_text='Labor de cosecha asociada (única por producto)', on_delete=django.db.models.deletion.CASCADE, related_name='producto_cosechado', to='cooperativa.labor')),
                ('parcela', models.ForeignKey(blank=True, help_text='Parcela de donde proviene el producto (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_cosechados', to='cooperativa.parcela')),
            ],
            options={
                'verbose_name': 'Producto Cosechado',
                'verbose_name_plural': 'Productos Cosechados',
                'db_table': 'producto_cosechado',
                'ordering': ['-fecha_cosecha', '-creado_en'],
                'indexes': [models.Index(fields=['fecha_cosecha'], name='producto_co_fecha_c_b521a5_idx'), models.Index(fields=['estado'], name='producto_co_estado_415cea_idx'), models.Index(fields=['lote'], name='producto_co_lote_28128c_idx')],
            },
        ),
    ]
