# Generated by Django 5.2.5 on 2025-11-03 19:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0002_labor_productocosechado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(help_text='Nombre del cliente (si no es socio)', max_length=200)),
                ('cliente_email', models.EmailField(blank=True, help_text='Email del cliente', max_length=254, null=True)),
                ('cliente_telefono', models.CharField(blank=True, help_text='Teléfono del cliente', max_length=20, null=True)),
                ('cliente_direccion', models.TextField(blank=True, help_text='Dirección de entrega', null=True)),
                ('numero_pedido', models.CharField(help_text='Número único de pedido (generado automáticamente)', max_length=50, unique=True)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del pedido')),
                ('fecha_entrega_estimada', models.DateField(blank=True, help_text='Fecha estimada de entrega', null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, help_text='Fecha real de entrega', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal del pedido (sin impuestos)', max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='El subtotal no puede ser negativo')])),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, help_text='Impuestos aplicados', max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Los impuestos no pueden ser negativos')])),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado', max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='El descuento no puede ser negativo')])),
                ('total', models.DecimalField(decimal_places=2, help_text='Total del pedido (subtotal + impuestos - descuento)', max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='El total no puede ser negativo')])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', help_text='Estado actual del pedido', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del pedido', null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(blank=True, help_text='Socio que realiza el pedido (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='cooperativa.socio')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(help_text='Número único de recibo (generado automáticamente)', max_length=50, unique=True)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del pago')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto pagado', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='El monto debe ser mayor a 0')])),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('STRIPE', 'Tarjeta (Stripe)'), ('QR', 'Pago QR'), ('OTRO', 'Otro')], help_text='Método de pago utilizado', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('REEMBOLSADO', 'Reembolsado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', help_text='Estado del pago', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='ID del Payment Intent de Stripe', max_length=200, null=True, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, help_text='ID del Charge de Stripe', max_length=200, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='ID del Cliente en Stripe', max_length=200, null=True)),
                ('referencia_bancaria', models.CharField(blank=True, help_text='Referencia bancaria (para transferencias)', max_length=100, null=True)),
                ('banco', models.CharField(blank=True, help_text='Nombre del banco (para transferencias)', max_length=100, null=True)),
                ('comprobante_archivo', models.CharField(blank=True, help_text='URL o path del comprobante de pago', max_length=500, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del pago', null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('procesado_por', models.ForeignKey(blank=True, help_text='Usuario que procesó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_procesados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(help_text='Pedido al que corresponde este pago', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cooperativa.pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(help_text='Nombre del producto', max_length=200)),
                ('producto_descripcion', models.TextField(blank=True, help_text='Descripción del producto', null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='La cantidad debe ser mayor a 0')])),
                ('unidad_medida', models.CharField(default='kg', help_text='Unidad de medida', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El precio no puede ser negativo')])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal (cantidad * precio_unitario)', max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='El subtotal no puede ser negativo')])),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto_cosechado', models.ForeignKey(blank=True, help_text='Producto cosechado vendido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido', to='cooperativa.productocosechado')),
                ('pedido', models.ForeignKey(help_text='Pedido al que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cooperativa.pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
                'db_table': 'detalle_pedido',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['numero_pedido'], name='pedido_numero__dc4441_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_pedido'], name='pedido_fecha_p_628264_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='pedido_estado_01ae34_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['numero_recibo'], name='pago_numero__205aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_pago'], name='pago_fecha_p_e0ee42_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado'], name='pago_estado_e7b4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['metodo_pago'], name='pago_metodo__d019a7_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['stripe_payment_intent_id'], name='pago_stripe__724d7a_idx'),
        ),
    ]
