# Generated by Django 5.2.5 on 2025-11-03 21:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0003_pedido_pago_detallepedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(help_text='Número único de pedido (generado automáticamente)', max_length=50, unique=True)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del pedido')),
                ('fecha_entrega_solicitada', models.DateField(blank=True, help_text='Fecha en que el socio necesita los insumos', null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, help_text='Fecha real de entrega', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal del pedido', max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='El subtotal no puede ser negativo')])),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado', max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='El descuento no puede ser negativo')])),
                ('total', models.DecimalField(decimal_places=2, help_text='Total del pedido (subtotal - descuento)', max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='El total no puede ser negativo')])),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('EN_PREPARACION', 'En Preparación'), ('LISTO_ENTREGA', 'Listo para Entrega'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', help_text='Estado actual del pedido', max_length=20)),
                ('motivo_solicitud', models.TextField(blank=True, help_text='Motivo o justificación de la solicitud', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales', null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, help_text='Fecha de aprobación', null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, help_text='Usuario que aprobó el pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_insumos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('entregado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la entrega', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_insumos_entregados', to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(help_text='Socio que solicita los insumos', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_insumos', to='cooperativa.socio')),
            ],
            options={
                'verbose_name': 'Pedido de Insumo',
                'verbose_name_plural': 'Pedidos de Insumos',
                'db_table': 'pedido_insumo',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='PagoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(help_text='Número único de recibo', max_length=50, unique=True)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del pago')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto pagado', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='El monto debe ser mayor a 0')])),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('DESCUENTO_PRODUCCION', 'Descuento de Producción'), ('CREDITO', 'Crédito'), ('OTRO', 'Otro')], help_text='Método de pago utilizado', max_length=30)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('PARCIAL', 'Parcial'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', help_text='Estado del pago', max_length=20)),
                ('referencia_bancaria', models.CharField(blank=True, help_text='Referencia bancaria (para transferencias)', max_length=100, null=True)),
                ('banco', models.CharField(blank=True, help_text='Nombre del banco', max_length=100, null=True)),
                ('comprobante_archivo', models.CharField(blank=True, help_text='URL o path del comprobante', max_length=500, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del pago', null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Usuario que registró el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_insumo_registrados', to=settings.AUTH_USER_MODEL)),
                ('pedido_insumo', models.ForeignKey(help_text='Pedido al que corresponde este pago', on_delete=django.db.models.deletion.CASCADE, related_name='pagos_insumo', to='cooperativa.pedidoinsumo')),
            ],
            options={
                'verbose_name': 'Pago de Insumo',
                'verbose_name_plural': 'Pagos de Insumos',
                'db_table': 'pago_insumo',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_insumo', models.CharField(choices=[('SEMILLA', 'Semilla'), ('PESTICIDA', 'Pesticida'), ('FERTILIZANTE', 'Fertilizante')], help_text='Tipo de insumo', max_length=20)),
                ('insumo_nombre', models.CharField(help_text='Nombre del insumo (snapshot)', max_length=200)),
                ('insumo_descripcion', models.TextField(blank=True, help_text='Descripción del insumo', null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad solicitada', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='La cantidad debe ser mayor a 0')])),
                ('unidad_medida', models.CharField(help_text='Unidad de medida', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento del pedido', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El precio no puede ser negativo')])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal (cantidad * precio_unitario)', max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='El subtotal no puede ser negativo')])),
                ('temporada_aplicada', models.CharField(blank=True, help_text='Temporada del precio aplicado', max_length=20, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('fertilizante', models.ForeignKey(blank=True, help_text='Fertilizante solicitado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido', to='cooperativa.fertilizante')),
                ('pesticida', models.ForeignKey(blank=True, help_text='Pesticida solicitado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido', to='cooperativa.pesticida')),
                ('semilla', models.ForeignKey(blank=True, help_text='Semilla solicitada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido', to='cooperativa.semilla')),
                ('pedido_insumo', models.ForeignKey(help_text='Pedido al que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cooperativa.pedidoinsumo')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido de Insumo',
                'verbose_name_plural': 'Detalles de Pedidos de Insumos',
                'db_table': 'detalle_pedido_insumo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PrecioTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_insumo', models.CharField(choices=[('SEMILLA', 'Semilla'), ('PESTICIDA', 'Pesticida'), ('FERTILIZANTE', 'Fertilizante')], help_text='Tipo de insumo', max_length=20)),
                ('temporada', models.CharField(choices=[('VERANO', 'Verano'), ('INVIERNO', 'Invierno'), ('PRIMAVERA', 'Primavera'), ('OTOÑO', 'Otoño')], help_text='Temporada del año', max_length=20)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la temporada')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin de la temporada')),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio de venta por unidad', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El precio no puede ser negativo')])),
                ('precio_mayoreo', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de mayoreo (opcional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='El precio no puede ser negativo')])),
                ('cantidad_minima_mayoreo', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad mínima para precio de mayoreo', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='La cantidad no puede ser negativa')])),
                ('activo', models.BooleanField(default=True, help_text='Si el precio está activo')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fertilizante', models.ForeignKey(blank=True, help_text='Fertilizante (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precios_temporada', to='cooperativa.fertilizante')),
                ('pesticida', models.ForeignKey(blank=True, help_text='Pesticida (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precios_temporada', to='cooperativa.pesticida')),
                ('semilla', models.ForeignKey(blank=True, help_text='Semilla (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precios_temporada', to='cooperativa.semilla')),
            ],
            options={
                'verbose_name': 'Precio por Temporada',
                'verbose_name_plural': 'Precios por Temporada',
                'db_table': 'precio_temporada',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidoinsumo',
            index=models.Index(fields=['numero_pedido'], name='pedido_insu_numero__479179_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoinsumo',
            index=models.Index(fields=['socio', 'estado'], name='pedido_insu_socio_i_b35794_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoinsumo',
            index=models.Index(fields=['fecha_pedido'], name='pedido_insu_fecha_p_5961e9_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoinsumo',
            index=models.Index(fields=['numero_recibo'], name='pago_insumo_numero__b2c517_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoinsumo',
            index=models.Index(fields=['pedido_insumo', 'estado'], name='pago_insumo_pedido__29727a_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoinsumo',
            index=models.Index(fields=['fecha_pago'], name='pago_insumo_fecha_p_78dc02_idx'),
        ),
        migrations.AddIndex(
            model_name='preciotemporada',
            index=models.Index(fields=['tipo_insumo', 'temporada'], name='precio_temp_tipo_in_7cf5e9_idx'),
        ),
        migrations.AddIndex(
            model_name='preciotemporada',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='precio_temp_fecha_i_3b73c6_idx'),
        ),
    ]
