# Generated by Django 5.0.1 on 2025-10-09 02:02

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0008_rol_es_sistema_alter_rol_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='tipo_tratamiento',
            field=models.CharField(choices=[('FERTILIZANTE', 'Fertilizante'), ('PESTICIDA', 'Pesticida'), ('HERBICIDA', 'Fungicida'), ('REGULADOR', 'Regulador de Crecimiento'), ('RIEGO', 'Riego'), ('LABOR', 'Labor Cultural'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.CreateModel(
            name='Semilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(help_text='Especie de la semilla (ej: Maíz, Trigo, Soya)', max_length=100, validators=[django.core.validators.RegexValidator(message='Especie solo puede contener letras, espacios, guiones y puntos', regex='^[a-zA-ZÀ-ÿ\\s\\-\\.]+$')])),
                ('variedad', models.CharField(blank=True, help_text='Variedad específica de la semilla', max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Variedad solo puede contener letras, números, espacios, guiones y puntos', regex='^[a-zA-ZÀ-ÿ0-9\\s\\-\\.]+$')])),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad disponible en kilogramos', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='La cantidad no puede ser negativa')])),
                ('unidad_medida', models.CharField(default='kg', help_text='Unidad de medida (kg, g, toneladas, etc.)', max_length=20)),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento de la semilla')),
                ('porcentaje_germinacion', models.DecimalField(decimal_places=2, help_text='Porcentaje de germinación (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='El porcentaje no puede ser negativo'), django.core.validators.MaxValueValidator(100, message='El porcentaje no puede exceder 100%')])),
                ('lote', models.CharField(blank=True, help_text='Número de lote del proveedor', max_length=50, null=True)),
                ('proveedor', models.CharField(blank=True, help_text='Nombre del proveedor', max_length=100, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario por kilogramo', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='El precio no puede ser negativo')])),
                ('ubicacion_almacen', models.CharField(blank=True, help_text='Ubicación física en el almacén', max_length=100, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADA', 'Agotada'), ('VENCIDA', 'Vencida'), ('RESERVADA', 'Reservada')], default='DISPONIBLE', help_text='Estado actual de la semilla', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Semilla',
                'verbose_name_plural': 'Semillas',
                'db_table': 'semilla',
                'ordering': ['-creado_en'],
                'unique_together': {('especie', 'variedad', 'lote')},
            },
        ),
    ]
