# Generated by Django 5.0.1 on 2025-10-09 04:54

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0009_alter_tratamiento_tipo_tratamiento_semilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(help_text='Nombre comercial del fertilizante', max_length=100, validators=[django.core.validators.RegexValidator(message='Nombre comercial solo puede contener letras, números, espacios, guiones, puntos y paréntesis', regex='^[a-zA-ZÀ-ÿ0-9\\s\\-\\.\\(\\)]+$')])),
                ('tipo_fertilizante', models.CharField(choices=[('QUIMICO', 'Químico'), ('ORGANICO', 'Orgánico'), ('FOLIARES', 'Foliares'), ('RAIZ', 'De raíz'), ('MICRONUTRIENTES', 'Micronutrientes'), ('CALCAREO', 'Calcareo'), ('OTRO', 'Otro')], help_text='Tipo de fertilizante', max_length=20)),
                ('composicion_npk', models.CharField(help_text='Composición NPK (ej: 10-10-10)', max_length=20, validators=[django.core.validators.RegexValidator(message='Composición NPK debe tener formato N-P-K (ej: 10-10-10, 20-10-10+5)', regex='^[0-9\\-]+-[0-9\\-]+-[0-9\\-]+(\\+[0-9]+)?$')])),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad disponible', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='La cantidad no puede ser negativa')])),
                ('unidad_medida', models.CharField(default='kg', help_text='Unidad de medida (kg, toneladas, L, etc.)', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento del fertilizante (opcional para orgánicos)', null=True)),
                ('lote', models.CharField(help_text='Número único del lote', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Lote solo puede contener letras mayúsculas, números, guiones, guiones bajos y puntos', regex='^[A-Z0-9\\-_\\.]+$')])),
                ('proveedor', models.CharField(help_text='Nombre del proveedor', max_length=100, validators=[django.core.validators.RegexValidator(message='Proveedor solo puede contener letras, números, espacios y caracteres especiales limitados', regex='^[a-zA-ZÀ-ÿ0-9\\s\\-\\.\\&\\(\\)]+$')])),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El precio no puede ser negativo')])),
                ('ubicacion_almacen', models.CharField(help_text='Ubicación física en el almacén', max_length=100, validators=[django.core.validators.RegexValidator(message='Ubicación solo puede contener letras, números, espacios, guiones, puntos y barras', regex='^[a-zA-ZÀ-ÿ0-9\\s\\-\\.\\/]+$')])),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('VENCIDO', 'Vencido'), ('EN_CUARENTENA', 'En Cuarentena'), ('RECHAZADO', 'Rechazado')], default='DISPONIBLE', help_text='Estado actual del fertilizante', max_length=20)),
                ('dosis_recomendada', models.CharField(blank=True, help_text='Dosis recomendada por hectárea', max_length=50, null=True)),
                ('materia_orgánica', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de materia orgánica (para fertilizantes orgánicos)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='La materia orgánica no puede ser negativa'), django.core.validators.MaxValueValidator(100, message='La materia orgánica no puede exceder 100%')])),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fertilizante',
                'verbose_name_plural': 'Fertilizantes',
                'db_table': 'fertilizante',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pesticida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(help_text='Nombre comercial del pesticida', max_length=100, validators=[django.core.validators.RegexValidator(message='Nombre comercial solo puede contener letras, números, espacios, guiones, puntos y paréntesis', regex='^[a-zA-ZÀ-ÿ0-9\\s\\-\\.\\(\\)]+$')])),
                ('ingrediente_activo', models.CharField(help_text='Principio activo del pesticida', max_length=100, validators=[django.core.validators.RegexValidator(message='Ingrediente activo solo puede contener letras, números, espacios, guiones, puntos y paréntesis', regex='^[a-zA-ZÀ-ÿ0-9\\s\\-\\.\\(\\)]+$')])),
                ('tipo_pesticida', models.CharField(choices=[('INSECTICIDA', 'Insecticida'), ('FUNGICIDA', 'Fungicida'), ('HERBICIDA', 'Herbicida'), ('NEMATICIDA', 'Nematicida'), ('ACARICIDA', 'Acaricida'), ('BACTERICIDA', 'Bactericida'), ('MOLUSQUICIDA', 'Molusquicida'), ('RODENTICIDA', 'Rodenticida'), ('OTRO', 'Otro')], help_text='Tipo de pesticida', max_length=20)),
                ('concentracion', models.CharField(help_text='Concentración del ingrediente activo', max_length=50, validators=[django.core.validators.RegexValidator(message='Concentración debe tener formato válido (ej: 50% WP, 200 g/L)', regex='^[0-9\\.\\,\\s\\%\\-\\(\\)a-zA-Z]+$')])),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad disponible', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='La cantidad no puede ser negativa')])),
                ('unidad_medida', models.CharField(default='L', help_text='Unidad de medida (L, kg, ml, g, etc.)', max_length=20)),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento del pesticida')),
                ('lote', models.CharField(help_text='Número único del lote', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Lote solo puede contener letras mayúsculas, números, guiones, guiones bajos y puntos', regex='^[A-Z0-9\\-_\\.]+$')])),
                ('proveedor', models.CharField(help_text='Nombre del proveedor', max_length=100, validators=[django.core.validators.RegexValidator(message='Proveedor solo puede contener letras, números, espacios y caracteres especiales limitados', regex='^[a-zA-ZÀ-ÿ0-9\\s\\-\\.\\&\\(\\)]+$')])),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El precio no puede ser negativo')])),
                ('ubicacion_almacen', models.CharField(help_text='Ubicación física en el almacén', max_length=100, validators=[django.core.validators.RegexValidator(message='Ubicación solo puede contener letras, números, espacios, guiones, puntos y barras', regex='^[a-zA-ZÀ-ÿ0-9\\s\\-\\.\\/]+$')])),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('VENCIDO', 'Vencido'), ('EN_CUARENTENA', 'En Cuarentena'), ('RECHAZADO', 'Rechazado')], default='DISPONIBLE', help_text='Estado actual del pesticida', max_length=20)),
                ('registro_sanitario', models.CharField(blank=True, help_text='Número de registro sanitario', max_length=50, null=True)),
                ('dosis_recomendada', models.CharField(blank=True, help_text='Dosis recomendada por hectárea', max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pesticida',
                'verbose_name_plural': 'Pesticidas',
                'db_table': 'pesticida',
                'ordering': ['-creado_en'],
            },
        ),
    ]
