# Generated by Django 5.0.1 on 2025-10-09 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0010_fertilizante_pesticida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizante',
            name='nombre_comercial',
            field=models.CharField(help_text='Nombre comercial del fertilizante', max_length=100, validators=[django.core.validators.RegexValidator(message='Nombre comercial solo puede contener letras, números, espacios, guiones, puntos, paréntesis y porcentaje', regex='^[a-zA-ZÀ-ÿ0-9\\s\\-\\.\\(\\)\\%]+$')]),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud en grados decimales', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180, message='Longitud debe estar entre -180 y 180'), django.core.validators.MaxValueValidator(180, message='Longitud debe estar entre -180 y 180')]),
        ),
        migrations.AlterField(
            model_name='pesticida',
            name='concentracion',
            field=models.CharField(help_text='Concentración del ingrediente activo', max_length=50, validators=[django.core.validators.RegexValidator(message='Concentración debe tener formato válido (ej: 50%% WP, 200 g/L)', regex='^[0-9\\.\\,\\s\\%\\-\\(\\)a-zA-Z\\+]+$')]),
        ),
        migrations.AlterField(
            model_name='pesticida',
            name='ingrediente_activo',
            field=models.CharField(help_text='Principio activo del pesticida', max_length=100, validators=[django.core.validators.RegexValidator(message='Ingrediente activo solo puede contener letras, números, espacios, guiones, puntos, paréntesis y signo más', regex='^[a-zA-ZÀ-ÿ0-9\\s\\-\\.\\(\\)\\+]+$')]),
        ),
    ]
