# Generated by Django 5.0.1 on 2025-10-09 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0011_alter_fertilizante_nombre_comercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitud en grados decimales', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180, message='Longitud debe estar entre -180 y 180'), django.core.validators.MaxValueValidator(180, message='Longitud debe estar entre -180 y 180')]),
        ),
    ]
